### ISSUE TITLE
Warning: This plugin is NOT eslint, it is using JSHINT under the hood

### ISSUE THREAD

**Issue by sirlancelot** [azeemba/eslint-plugin-json#13]
Just a warning to everyone who thinks this is using eslint to lint json files. It merely wraps JSHINT and uses the default JSHINT settings to lint json files.

**Comment by azeemba** [comment]
Haha why exactly is this warning needed? It is a [plugin](http://eslint.org/docs/developer-guide/working-with-plugins) to expand eslint's features. eslint doesn't supporting linting JSON files and this plugin adds that ability (admittedly in a hilariously roundabout away).

**Comment by sirlancelot** [comment]
Just a heads up for those who might be tempted to "fix" or "customize" the linting. I spent too much time myself trying to figure out why it didn't use my provided eslintrc.

It deserves a warning because it doesn't do what anyone would expect it to do.

**Comment by azeemba** [comment]
So there are two points here. The fact that this plugin uses jshint in the background is an implementation detail and that can be swapped out in the future. However, eslint options will not be supported for JSON linting. This is because JSON is much stricter than JS code. Preferring single quotes in my JS code doesn't change the fact that JSON requires double quotes.

If support for certain configuration options (like spacing) are added, those would go in eslintrc as plugin specific options. 

Anyways, this issue doesn't really add any value at the moment so I will close it.

**Comment by autra** [comment]
@azeemba you need to acknowledge that you have `eslint` in your repo name. It is misleading and @sirlancelot wasn't the only one fooled... Intellectual honesty should make you add a warning in your README. After all, if it's only an implementation detail, why would you hide it?

You can replace

> lint json files

by

> lint json files with jshint using eslint architecture.

It would be clearer and ppl would know what to expect: .eslintrc are not read, it depends on jshint etc... Some people might not care, some people will, everybody will be happier.

**Comment by azeemba** [comment]
I think there is some confusion about what this plugin is supposed to do. 
A major concern seems to be that eslint-plugin-json doesn't read `.eslintrc`. That is always going to be true. A rule you configure for javascript doesn't apply to JSON simply because JSON is a lot more stricter. In the future, we can add options just for our plugin but it will never read flags for javascript.

The point of having `eslint` in the name is moot. That is how eslint plugins are supposed to be named. 

I do understand that doing json linting via jshint is hacky. I just don't see how questions of "intellectual honesty" are cropping up. Dependencies of the package show up on npm and are easily visible in github by going into the `package.json`.  

If you really care, you can send a PR that adds a line in the README explaining that the current implementation uses jshint. If you care even more, you can send a PR to switch the implementation to use https://github.com/zaach/jsonlint or something like that.

**Comment by sirlancelot** [comment]
@autra I think the best we can do at this point is just not use this module and let as many people know that this module is not related to eslint in any way.

**Comment by sirlancelot** [comment]
I rather like the idea of #11 where it attempts to create a valid `.js` which can then be run natively through eslint. Unfortunately, that PR still passes in to JSHint. I may take a stab at it at some point but I'd more likely make my own module if that were so.

**Comment by azeemba** [comment]
> this module is not related to eslint in any way

You keep saying this, what does that even mean? It is an eslint plugin. Most plugins don't use eslint because if eslint supported the use case natively, they wouldn't need to exist.

Of course you are free to not use this module and explain your side to other people. I just hope you don't spread misinformation. 

If you do have an implementation that works better from a user's perspective (i.e. reports better errors, supports `--fix`, supports additional JSON-only configuration like indent length/type but ignores JS configuration options like `quotes`), I will be more than happy to accept such a PR. 
Hell, if you prefer and if it works well enough I will be willing to give up the package name on NPM to minimize fragmentation in the community.
