### ISSUE TITLE
Support to lint indent, object-property-newline and comma-style rules

### ISSUE THREAD

**Issue by weizhenye** [azeemba/eslint-plugin-json#7]
As a subset of JavaScript object, JSON should be linted by those rules.
Maybe there are ohter rules I missed.

**Comment by azeemba** [comment]
I totally agree that this isn't the "right" way to do this. I even stumbled onto a [comment](http://webcache.googleusercontent.com/search?q=cache:Oi6GtEIY8jQJ:www.gitterforum.com/discussion/eslint-eslint%3Fpage%3D182+&cd=12&hl=en&ct=clnk&gl=us) from @ilyavolodin discussing this! 

I will mark this issue as "help wanted". If anyone wants to send a PR that uses eslint itself to do the json linting, I would be more than happy to accept it.

**Comment by richardpringle** [comment]
@azeemba, not sure what the best way to go about doing this is but I have thought out a fix for this issue as well as #8. It's a little bit hacky, I will admit... but who cares if this is just formatting.

`JSON.stringify(value, replacer, space)` has that last arguments that takes spacing into account.

We can have one rule that goes with this plugin which is the argument for the `space` param (no idea how to set a rule specific to a plugin or if that's even possible) and another rule for a new line at  the end of the file. 

I'm already running all my json files through `json.stringify(contents, null, '\t') + '\n'` but it would be nice to have a more concise way of enforcing formatting from my team with specified rules.

So we lint in order:
 - `jshint.JSHINT` (because it gives better errors than "unexpected token")
 - `JSON.stringify(val, null, spacing)` where spacing a rule that the user can specify
 - check for new line

I know how to put in all the logic but I'm not familiar with `eslint-plugin` conventions/configurations. If you could advise that would be much appreciated. Otherwise, I will read up on the plugin docs for `eslint`.

Cheers!

(thanks for this wonderful module by the way)

**Comment by azeemba** [comment]
@richardpringle I have updated https://github.com/azeemba/eslint-plugin-json/issues/8#issuecomment-441543606 with more info on how `--fix` can be supported.

In the meanwhile I will close this issue since I think the new implementation is a better replacement for JSHint.
