### ISSUE TITLE
Finding duplicate values instead of keys

### ISSUE THREAD

**Issue by Bassadin** [azeemba/eslint-plugin-json#81]
Is it at all feasible to create a rule that checks for duplicate (or similar) _values_ rather than keys? I'm not all too familiar with eslint plugin development, but I recently learned about the [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance) and I thought it'd be a great addition to lint our i18n language files with.

**Comment by azeemba** [comment]
Thanks for creating this issue.

Multiple keys mapping to the same or similar values is not an issue at the JSON level. I can see how its an issue in specific use cases but I think validation for that fits better in a custom plugin for that specific use case. 

Since this is not a about an error in JSON semantics, I will close this issue.

**Comment by Bassadin** [comment]
Thanks for your feedback!
